# Site settings
title: Professional On Demand SiteCore Services
description: Sitecore Mentoring
baseurl: "/SiteCore" # the subpath of your site, e.g. /blog
url: "https://ptsatheesh.github.io" # the base hostname & protocol for your site  

# User settings
username: Saki
user_description: Saki at SiteCore Managed Services
email: ptsatheesh@gmail.com
twitter_username: ptsatheesh
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Mentoring Help
    url: /series
  - title: Training
    url: /tags
  - title: Projects
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
